### ISSUE TITLE
Fail to integrate LDDI-Exporter in Eclipse Smarthome

### ISSUE THREAD

**Issue by mdntuda** [universAAL/lddi#240] opened 2017-06-24 17:22 UTC
Hello everyone,

since there is no beginner forum, I hope I will not disturb some one with my basic questions. For this, please do not shoot me. 

I am using Debian Jessie, Oracle Java SDK 8, Eclipse Smarthome(openHAB 2.1). Now I like to integrate LDDI-Exporter. I have done every thing which is mentioned in the Wiki page. Till step 7, everything was fine. In step 7, I get the error message: Error executing command:Error
I realise that, with feature:list | grep uAAL* the bundle which I want to install is listed. Karaf shows me this after the command:
uAAL-MW.Smarthome                           | 3.4.1.SNAPSHOT   |          | Uninstalled | universAAL-3.4.1-SNAPSHOT            | The universAAL bundles for Eclipse Smarthome Kara
uAAL-Ont.Smarthome                          | 3.4.1.SNAPSHOT   |          | Uninstalled | universAAL-3.4.1-SNAPSHOT            | The Smarthome Ontology bundles for Eclipse Smarth
uAAL-LDDI.Smarthome                         | 3.4.1.SNAPSHOT   |          | Uninstalled | universAAL-3.4.1-SNAPSHOT            | The Smarthome LDDI Exporter bundles for Eclipse S

Obviously uAAL-LDDI.Smarthome exists, but I can not install it. 
A closer look at the error with the command log:display -n 1 I get this:

19:09:42.917 [ERROR] [apache.karaf.shell.support.ShellUtil] - Exception caught while executing command
org.apache.karaf.features.internal.util.MultiException: Error
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:84)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:363)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:360)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:187)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[8:org.apache.karaf.features.core:4.0.8]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: java.io.IOException: Error downloading mvn:org.universAAL.middleware/mw.container.xfaces.osgi/3.4.1-SNAPSHOT
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)[8:org.apache.karaf.features.core:4.0.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_131]
	... 3 more
Caused by: java.io.IOException: Error resolving artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT: [Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.1/), Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in apache (http://repository.apache.org/content/groups/snapshots-group/), Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/snapshots/), Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in ops4j.sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/ops4j-snapshots/), Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in spring-ebr-repository (http://repository.springsource.com/maven/bundles/external/), Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in repo_2030071354 (http://depot.universaal.org/maven-repo/snapshots/), Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.1.0.nightly/), Could not find artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT in openhab (https://openhab.jfrog.io/openhab/online-repo-snapshot/2.1/)]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:36)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)[8:org.apache.karaf.features.core:4.0.8]
	... 7 more
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.universAAL.middleware:mw.container.xfaces.osgi:jar:3.4.1-SNAPSHOT
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705)[7:org.ops4j.pax.url.mvn:2.5.2]
	... 12 more

I do not know how to deal with these kind of errors. Can someone please help me? 
Do I miss some really important step during the installation, which I have to make it work? 

Thank you very much and best regards,
mdn

**Comment by cstockloew** [comment] 2017-06-24 18:21
Hi,

this is just the right place for questions ;-)

We are currently doing some refactoring of the code, hence, there may be some problems with the latest development version. Normally, I could advise you to use the latest release version, but, unfortunately, the smarthome module was added after the last release.

The problem is an outdated karaf feature that still contains mw.container.xfaces.osgi. This bundle was removed completely. It is fixed in GIT, but was not deployed yet. I am currently deploying; the new version should be available in a few minutes and then you can give it a try.

Also, the smarthome karaf feature is currently a separate feature. All other bundles in LDDI are using the LDDI feature and smarthome needs to be integrated correctly. This might be done in the next days.

BR,
CS

**Comment by Alfiva** [comment] 2017-06-26 06:33
Just some insight: The uAAL smarthome karaf feature has to be kept separate from the main "official" LDDI feature because of possible conflicts of that one with the Eclipse SmartHome Karaf setup. I will later check if it needs fixes and update this thread when I do.

**Closed** 2018-04-18 10:28 UTC
